spring:
  config:
    import: classpath:zeardle.yml
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: 1250958538558279742
            client-secret: 7UGNJwPIumCPxjAIJxo79kCpf0LjihpK
            scope: identify, webhook.incoming
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Discord
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: id
  profiles:
    include:
      - zeardle

